apiVersion: v1
kind: Service
metadata:
  name: {{ include "insightengine.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ include "insightengine.fullname" . }}
    {{- include "insightengine.labels.standard" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  {{- with .Values.service.loadBalancerIP }}
  loadBalancerIP: {{ . | quote }}
  {{- end }}
  ports:
    - name: http
      port: {{ include "insightengine.servicePort" . | int }}
      targetPort: http
      protocol: TCP
  selector:
    app: {{ include "insightengine.fullname" . }}
